### Register a new client
POST http://localhost:4000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Елизавета",
  "email": "leonora.kilback@hotmail.com",
  "password": "123456",
  "gender": "Female",
  "role": "Client",
  "location": "Pionerskaya"
}

### Register a new coach
POST http://localhost:4000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Никита",
  "email": "casper_walter@hotmail.com",
  "password": "123456",
  "gender": "Male",
  "birthday": "1970-11-03",
  "role": "Coach",
  "location": "Zvezdnaya"
}

### Logout
GET http://localhost:4000/api/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDEzMWYzMjVkNmNiZTc2OWRjNDZlYmQiLCJlbWFpbCI6ImxpZGlhLmNhc2hAZXhhbXBsZS5jb20iLCJuYW1lIjoi0JbQsNC90L3QsCIsInJvbGUiOiJDbGllbnQiLCJpYXQiOjE2ODAxNzkxOTEsImV4cCI6MTY4MDE4MDA5MX0._kQaHgZ9JwQcaLUQ-pDH8hndB6jKM3HAAwPVUvl-1D0

### Login a client
POST http://localhost:4000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "leonora.kilback@hotmail.com",
  "password": "1234567"
}

### Login a coach
POST http://localhost:4000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "casper_walter@hotmail.com",
  "password": "123456"
}

### Get fresh tokens
GET http://localhost:4000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDEzMWYzMjVkNmNiZTc2OWRjNDZlYmQiLCJlbWFpbCI6ImxpZGlhLmNhc2hAZXhhbXBsZS5jb20iLCJuYW1lIjoi0JbQsNC90L3QsCIsInJvbGUiOiJDbGllbnQiLCJpYXQiOjE2ODAxODI3MzEsImV4cCI6MTY4MDc4NzUzMX0.MUFjf54I87Llf_78cnm0Wr7Eihx6-ELMYl0dNYTHG70
