export enum UserEvent {
  CheckAuth = 'CheckAuth',
  CheckEmail = 'CheckEmail',
  GetAll = 'GetAll',
  GetFriends = 'GetFriends',
  GetUser = 'GetUser',
  Login = 'Login',
  Logout = 'Logout',
  Refresh = 'Refresh',
  Register = 'Register',
  SaveClientDetails = 'SaveClientDetails',
  SaveCoachDetails = 'SaveCoachDetails',
  ToggleFriend = 'ToggleFriend',
  UpdateProfile = 'UpdateProfile',
  Verify = 'Verify',
}
