### Get alerts for the user
GET http://localhost:4000/api/alert
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDNmZWMzMzYwZTJiNGRhZjk5MjVkNWIiLCJlbWFpbCI6InJvbm5pZS5sbG95ZEBleGFtcGxlLmNvbSIsIm5hbWUiOiLQmNCz0L7RgNGMIiwicm9sZSI6IkNsaWVudCIsImlhdCI6MTY4MjIzMzc1OCwiZXhwIjoxNjgyMjM0NjU4fQ.dtL0F-U82oD6NqPmG0ve8X3aD_v2fnFptGl9jKv30S8

### Delete the alert
DELETE http://localhost:4000/api/alert/6444d51e4bed1ebed75030b8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDNmZWMzMzYwZTJiNGRhZjk5MjVkNWIiLCJlbWFpbCI6InJvbm5pZS5sbG95ZEBleGFtcGxlLmNvbSIsIm5hbWUiOiLQmNCz0L7RgNGMIiwicm9sZSI6IkNsaWVudCIsImlhdCI6MTY4MjIzMzc1OCwiZXhwIjoxNjgyMjM0NjU4fQ.dtL0F-U82oD6NqPmG0ve8X3aD_v2fnFptGl9jKv30S8
