### Create a workout
POST localhost:3332/api/workout HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDExYjBjZjMzMmM2MTIxZjg2ODJhMGYiLCJlbWFpbCI6ImVkZGllLm1jY2x1cmVAZXhhbXBsZS5jb20iLCJuYW1lIjoi0JjQs9C-0YDRjCIsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY3ODg4OTkyNiwiZXhwIjoxNjc4ODkwODI2fQ.OQk7XdIII1Y6zgxgz-7D8dWA_J8BTI0jFAa3j0vmR2s

{
  "background": "background.jpg",
  "calories": 1320,
  "description":  "Упражнения укрепляют мышечный корсет, делают суставы более гибкими, улучшают осанку и координацию.",
  "duration": "Short",
  "gender":  "Common",
  "isSpecialOffer": false,
  "price":  0,
  "skill": "Beginner",
  "title":  "Energy",
  "type": "Pilates",
  "video":  "video.mp4"
}
