version: '3.5'
services:
  postgres-fit-friends-orders:
    image: postgres:14-alpine
    container_name: postgres-fit-friends-accounts
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "fit-friends-accounts"
    expose:
      - "5434"
    ports:
      - "5434:5434"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./db:/var/lib/postgresql/data
    command: -p 5434
    networks:
      - postgres-fit-friends-accounts

  pgadmin-fit-friends-orders:
    container_name: pgadmin-fit-friends-accounts
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "keks@htmlacademy.local"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"

    volumes:
      - ./db:/var/lib/pgadmin
    ports:
      - "8084:80"
    restart: unless-stopped
    networks:
      - postgres-fit-friends-accounts

networks:
  postgres-fit-friends-accounts:
    driver: bridge

