version: '3.5'
services:
  mongodb:
    image: mongo
    container_name: mongodb-fit-friends-files
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_ROOT_DATABASE: fit-friends-files
    ports:
      - "27019:27017"
    volumes:
      - ./db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/fit-friends-files --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongdb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express-fit-friends-files
    ports:
      - "8088:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://admin:123456@mongodb:27017/
