### Create a client profile
POST http://localhost:3333/api/profile/client
Content-Type: application/json

{
  "skill":  "Beginner",
  "trainings": "Йога",
  "duration":  "10-30 min",
  "caloriesTarget": 44,
  "caloriesPerDay":  55,
  "readiness": true
}

### Create a coach profile
POST http://localhost:3333/api/profile/coach
Content-Type: application/json

{
  "skill":  "Beginner",
  "trainings": "Йога",
  "certificate": "cert",
  "hasPersonalTrainings": true,
  "achievements": "Existence is pain to a meeseeks Jerry, and we will do anything to alleviate that pain."
}
