### Create an workout order
POST http://localhost:3334/api/order/workout HTTP/1.1
Content-Type: application/json

{
  "payment": "Visa",
  "coachId": "coachId",
  "price": 555,
  "purchaseType": "Workout",
  "quantity": 2,
  "serviceId":  14
}

### Get an order
GET http://localhost:3334/api/order/5 HTTP/1.1

### Get orders by userId
GET http://localhost:3334/api/order/my HTTP/1.1
