### Register a new client
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Игорь",
  "email": "ronnie.lloyd@example.com",
  "password": "123456",
  "gender": "Male",
  "role": "Client",
  "location": "Пионерская"
}

### Register a new coach
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Ангелина",
  "email": "darius.howard@example.com",
  "password": "123456",
  "gender": "Female",
  "birthday": "1980-04-22",
  "role": "Coach",
  "location": "Удельная"
}

### Logout
GET http://localhost:3333/api/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDBjZTJiNDM4ZTYzZjE2M2NhZjA3ZWMiLCJlbWFpbCI6ImxvbGEuZ2lsZXNAZXhhbXBsZS5jb20iLCJuYW1lIjoi0JDQvdCw0YHRgtCw0YHQuNGPIiwicm9sZSI6IkNsaWVudCIsImlhdCI6MTY3ODU2NjA2OCwiZXhwIjoxNjc4NTY2MDY4fQ.Gz4gDwagH5YBFpBf9zyfqs5LNGLeAo10kF6mhNaqDWQ

### Login a client
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "lidia.cash@example.com",
  "password": "123456"
}

### Login a coach
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "eddie.mcclure@example.com",
  "password": "123456"
}

### Get fresh tokens
GET http://localhost:3333/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDBjZTJiNDM4ZTYzZjE2M2NhZjA3ZWMiLCJlbWFpbCI6ImxvbGEuZ2lsZXNAZXhhbXBsZS5jb20iLCJuYW1lIjoi0JDQvdCw0YHRgtCw0YHQuNGPIiwicm9sZSI6IkNsaWVudCIsImlhdCI6MTY3ODYwNjg5MiwiZXhwIjoxNjc5MjExNjkyfQ.Z0Xggge41ZbjEOUSVWntnKMZxesIQG4wn2zTISan8e8
