version: '3.5'
services:
  postgres-fit-friends-gyms:
    image: postgres:14-alpine
    container_name: postgres-fit-friends-gyms
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'fit-friends-gyms'
    expose:
      - '5435'
    ports:
      - '5435:5435'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d test']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./db:/var/lib/postgresql/data
    command: -p 5435
    networks:
      - postgres-fit-friends-gyms

  pgadmin-fit-friends-orders:
    container_name: pgadmin-fit-friends-gyms
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'keks@htmlacademy.local'
      PGADMIN_DEFAULT_PASSWORD: 'test'
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    volumes:
      - ./db:/var/lib/pgadmin
    ports:
      - '8085:80'
    restart: unless-stopped
    networks:
      - postgres-fit-friends-gyms

networks:
  postgres-fit-friends-gyms:
    driver: bridge
