version: '3.5'
services:
  fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: "fit-friends.notification.fakesmtp"
    hostname: "fakesmtp"
    ports:
      - "5025:5025"
      - "1083:5080"

  mongodb:
    image: mongo
    container_name: fit-friends.notification.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: fit-friends-notification
    ports:
      - "27018:27017"
    volumes:
      - ./db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/fit-friends-notification --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongodb-express:
    image: mongo-express
    container_name: fit-friends.notification.mongo-express
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27017/
