### Get a detailed user unformation
GET http://localhost:4000/api/user/643fec3360e2b4daf9925d5b HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDQ0ZGNkOThlYWU5ZjQ4OWQ5YzYwNDIiLCJlbWFpbCI6Imxlb25vcmEua2lsYmFja0Bob3RtYWlsLmNvbSIsIm5hbWUiOiLQldC70LjQt9Cw0LLQtdGC0LAiLCJyb2xlIjoiQ2xpZW50IiwiaWF0IjoxNjg0MjY1ODM3LCJleHAiOjE2ODQyNjY3Mzd9.DpSZHWe4EpEFxfSh98n6DWLSCLg_drMXfrCrLR_g1gw

### Get all users
GET http://localhost:4000/api/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDEzMWYzMjVkNmNiZTc2OWRjNDZlYmQiLCJlbWFpbCI6ImxpZGlhLmNhc2hAZXhhbXBsZS5jb20iLCJuYW1lIjoi0JDQu9C40L3QsCIsInJvbGUiOiJDbGllbnQiLCJpYXQiOjE2Nzg5NzQ3NzAsImV4cCI6MTY3ODk3NTY3MH0.r52jhVYl0atKAmOp-sorZZT9egMyb7qmRGYJJ79MyIU

### Save client details
PATCH http://localhost:4000/api/user/client HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDQ0ZGNkOThlYWU5ZjQ4OWQ5YzYwNDIiLCJlbWFpbCI6Imxlb25vcmEua2lsYmFja0Bob3RtYWlsLmNvbSIsIm5hbWUiOiLQldC70LjQt9Cw0LLQtdGC0LAiLCJyb2xlIjoiQ2xpZW50IiwiaWF0IjoxNjgyMjM0ODE0LCJleHAiOjE2ODIyMzU3MTR9.x67BlE_XM3qEtZSvO8lSEBG5SfMun0TzWc1QwX4F_KA

{
  "skill":  "Amateur",
  "trainings": ["Yoga", "Crossfit", "Aerobics"],
  "duration":  "Normal",
  "caloriesTarget": 4000,
  "caloriesPerDay":  1200,
  "readiness": true,
  "info": "Привет! Я Катерина и мне 27 лет. Обожаю спорт и все, что с ним связанно. Регулярно хожу на тренировки по кроссфиту, также занимаюсь йогой, рястяжкой и пилатесом. Занимаюсь как с тренером индивидуально, так и на групповых занятиях. Люблю соревнования и челленджи, так что присоединяйтесь, давайте объединяться и заниматься вместе!)"
}

### Save coach details
PATCH http://localhost:4000/api/user/coach HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDQ0ZGNlMDhlYWU5ZjQ4OWQ5YzYwNDYiLCJlbWFpbCI6ImNhc3Blcl93YWx0ZXJAaG90bWFpbC5jb20iLCJuYW1lIjoi0J3QuNC60LjRgtCwIiwicm9sZSI6IkNvYWNoIiwiaWF0IjoxNjgyMjM0OTUxLCJleHAiOjE2ODIyMzU4NTF9.olTy_-Eiam4bYpbHx4Ts4fj95y0PNn_wNT-JJ0qNU9w

{
  "skill":  "Professional",
  "trainings": ["Yoga", "Boxing", "Crossfit"],
  "hasPersonalTrainings": false,
  "achievements":  "Привет! Меня зовут Иванова Валерия, мне 34 года. Я профессиональный тренер по боксу. Не боюсь пробовать новое, также увлекаюсь кроссфитом, йогой и силовыми тренировками."
}


### Update user profile
PATCH http://localhost:4000/api/user/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDEzMWYzMjVkNmNiZTc2OWRjNDZlYmQiLCJlbWFpbCI6ImxpZGlhLmNhc2hAZXhhbXBsZS5jb20iLCJuYW1lIjoi0JDQu9C40L3QsCIsInJvbGUiOiJDbGllbnQiLCJpYXQiOjE2Nzg5NzQ3NzAsImV4cCI6MTY3ODk3NTY3MH0.r52jhVYl0atKAmOp-sorZZT9egMyb7qmRGYJJ79MyIU

{
  "name": "Жанна",
  "skill":  "Professional",
  "trainings": ["Yoga", "Boxing"],
  "readiness": false,
  "duration":  "Long"
}

### Update a coach profile
PATCH http://localhost:4000/api/user/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDQ0ZGNlMDhlYWU5ZjQ4OWQ5YzYwNDYiLCJlbWFpbCI6ImNhc3Blcl93YWx0ZXJAaG90bWFpbC5jb20iLCJuYW1lIjoi0J3QuNC60LjRgtCwIiwicm9sZSI6IkNvYWNoIiwiaWF0IjoxNjgyMjM0OTUxLCJleHAiOjE2ODIyMzU4NTF9.olTy_-Eiam4bYpbHx4Ts4fj95y0PNn_wNT-JJ0qNU9w

{
  "hasPersonalTrainings": true
}


### Toggle a user as a friend
PATCH http://localhost:4000/api/user/friend/64244011dffce40fa32268f7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDEzMWYzMjVkNmNiZTc2OWRjNDZlYmQiLCJlbWFpbCI6ImxpZGlhLmNhc2hAZXhhbXBsZS5jb20iLCJuYW1lIjoi0JbQsNC90L3QsCIsInJvbGUiOiJDbGllbnQiLCJpYXQiOjE2ODAyMDg3NzEsImV4cCI6MTY4MDIwOTY3MX0._v4ooQDLihZLUBd6vOepJAuunYXNpUt2E7ansruG_24


### Get a list of user's friends
GET http://localhost:4000/api/user/friend HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDEzMWYzMjVkNmNiZTc2OWRjNDZlYmQiLCJlbWFpbCI6ImxpZGlhLmNhc2hAZXhhbXBsZS5jb20iLCJuYW1lIjoi0JbQsNC90L3QsCIsInJvbGUiOiJDbGllbnQiLCJpYXQiOjE2ODAyMDg3NzEsImV4cCI6MTY4MDIwOTY3MX0._v4ooQDLihZLUBd6vOepJAuunYXNpUt2E7ansruG_24


### Subsctibe to notification about a new workout
POST http://localhost:4000/api/user/6411b0cf332c6121f8682a0f/subscribe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDExYjBjZjMzMmM2MTIxZjg2ODJhMGYiLCJlbWFpbCI6ImVkZGllLm1jY2x1cmVAZXhhbXBsZS5jb20iLCJuYW1lIjoi0JjQs9C-0YDRjCIsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY3ODg4OTkyNiwiZXhwIjoxNjc4ODkwODI2fQ.OQk7XdIII1Y6zgxgz-7D8dWA_J8BTI0jFAa3j0vmR2s
